version: '3.8'

services:

  app:
    container_name: app
    stdin_open: true
    tty: true   # Enabled together with stdin_open so it won't raise an error when we are in pdb mode.
    build:
      context: .
      dockerfile: Dockerfile
    # initialize database, then run dummy command to keep container running
    command: /bin/bash -c "python /app/init_db.py && tail -f /dev/null"
    volumes:
      - .:/app
    networks:
      - btc-network
    ports:
      - "5000:5000"
    depends_on:
      - btc_janusgraph
      - btc_postgres_db

  btc_postgres_db:
    container_name: btc_postgres_db
    image: postgres
    restart: unless-stopped
    networks:
      - btc-network
    ports:
    - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ${DATABASE_FOLDER:-./data/btc_postgres_db}:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${DATABASE_NAME}
    - POSTGRES_USER=${DATABASE_USER}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  btc_janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: btc_janusgraph
    environment:
      # janusgraph.graph.set-vertex-id: true
      # janusgraph.graph.allow-custom-vid-types: true
      janusgraph.storage.backend: berkeleyje
      # janusgraph.storage.backend: cassandra
      # janusgraph.index.default.backend: lucene
    ports:
      - "${JANUSGRAPH_PORT:-8182}:${JANUSGRAPH_PORT:-8182}"
      - "8484:8184"
    networks:
      - btc-network
    volumes:
      - ${GRAPH_DB_FOLDER:-./data/btc_janusgraph}:/var/lib/janusgraph
    healthcheck:
      test: ["CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 60s
      retries: 4


networks:
  btc-network:
