"""Initial commit

Revision ID: 311321a333a7
Revises: 
Create Date: 2024-01-18 05:29:51.500784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311321a333a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_addr'), 'addresses', ['addr'], unique=False)
    op.create_table('blocks',
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('height')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address_owner_association',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'owner_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('index', sa.BigInteger(), nullable=True),
    sa.Column('index_in_block', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_height'], ['blocks.height'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_block_height'), 'transactions', ['block_height'], unique=False)
    op.create_index(op.f('ix_transactions_index'), 'transactions', ['index'], unique=False)
    op.create_index(op.f('ix_transactions_index_in_block'), 'transactions', ['index_in_block'], unique=False)
    op.create_index(op.f('ix_transactions_is_duplicate'), 'transactions', ['is_duplicate'], unique=False)
    op.create_table('manual_proportions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.BigInteger(), nullable=True),
    sa.Column('output_id', sa.BigInteger(), nullable=True),
    sa.Column('proportion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_id', 'output_id', name='_input_output_uc')
    )
    op.create_table('outputs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('index_in_tx', sa.Integer(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_output_tx_index_in_tx', 'outputs', ['tx_id', 'index_in_tx'], unique=False)
    op.create_index(op.f('ix_outputs_address_id'), 'outputs', ['address_id'], unique=False)
    op.create_index(op.f('ix_outputs_valid'), 'outputs', ['valid'], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('index_in_tx', sa.Integer(), nullable=True),
    sa.Column('prev_out_id', sa.Integer(), nullable=True),
    sa.Column('tx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prev_out_id'], ['outputs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inputs_prev_out_id'), 'inputs', ['prev_out_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inputs_prev_out_id'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_outputs_valid'), table_name='outputs')
    op.drop_index(op.f('ix_outputs_address_id'), table_name='outputs')
    op.drop_index('idx_output_tx_index_in_tx', table_name='outputs')
    op.drop_table('outputs')
    op.drop_table('manual_proportions')
    op.drop_index(op.f('ix_transactions_is_duplicate'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_index_in_block'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_index'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_height'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('address_owner_association')
    op.drop_table('owners')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_addresses_addr'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
