"""Updated mistakes in ManualProportion

Revision ID: fbc2e0a25168
Revises: 311321a333a7
Create Date: 2024-01-23 18:09:33.701776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc2e0a25168'
down_revision: Union[str, None] = '311321a333a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_proportions', 'input_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('manual_proportions', 'output_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('manual_proportions', 'proportion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('manual_proportions_output_id_fkey', 'manual_proportions', type_='foreignkey')
    op.drop_constraint('manual_proportions_input_id_fkey', 'manual_proportions', type_='foreignkey')
    op.create_foreign_key(None, 'manual_proportions', 'outputs', ['output_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'manual_proportions', 'inputs', ['input_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual_proportions', type_='foreignkey')
    op.drop_constraint(None, 'manual_proportions', type_='foreignkey')
    op.create_foreign_key('manual_proportions_input_id_fkey', 'manual_proportions', 'transactions', ['input_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('manual_proportions_output_id_fkey', 'manual_proportions', 'transactions', ['output_id'], ['id'], ondelete='CASCADE')
    op.alter_column('manual_proportions', 'proportion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('manual_proportions', 'output_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('manual_proportions', 'input_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
