@startuml

package "Bitcoin Data Model" {

    class Block {
        + height: int
    }

    class Transaction {
        + hash: string
        + index_in_block: int
        + is_duplicate: bool
        ---
        + block: Block
    }

    class Output {
        + index_in_tx: int
        + value: float
        + valid: bool
        ---
        + transaction: Transaction
        + address: Address
    }

    class Input {
        + index_in_tx: int
        ---
        + prev_out: Output
        + transaction: Transaction
    }

    class Address {
        + addr: string
    }

    Transaction "1" -- "many" Output : contains
    Transaction "1" -- "many" Input : contains
    Block "1" -- "many" Transaction : contains
    Output "1" -- "1" Address : Output Address
    Input "1" -- "1" Output : Previous Output

}

@enduml
