@startuml

package "Bitcoin Data Model" {

    class Block {
        + height: int
        ---
        + tx_set: Tx[*]
    }

    class Tx {
        + hash: string
        + index_in_block: int
        + is_duplicate: bool
        ---
        + output_set: Output[*]
        + input_set: Input[*]
        + block: Block
    }

    class Output {
        + index_in_tx: int
        + value: float
        ---
        + tx: Tx
        + address: Address
    }

    class Input {
        + index_in_tx: int
        ---
        + prev_out: Output
        + tx: Tx
    }

    class Address {
        + addr: string
    }

    Tx "1" -- "many" Output : contains
    Tx "1" -- "many" Input : contains
    Block "1" -- "many" Tx : contains
    Output "1" -- "1" Address : associated_with
    Input "1" -- "1" Output : spends

}

@enduml
