@startuml
title Bitcoin Data Graph

class owner {
    id : int
}

class address {
    + id : int
    ---
    + owner : Owner
}

class sent {
    + value : float
}

class output {
    + id : int
    + value : int
    + is_coinbase : bool
    + tainted : bool
    + label : String
    ---
    + address : Address
}

Owner "1" <-- "many" Address : Owns
Address "1" <-- "many" Output : Output Address
Output "many" -- "many" Output : Sent (Haircut Proportion)

@enduml
